apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: profile-scaledobject
spec:
  scaleTargetRef:
    name: profile
  minReplicaCount: 1
  maxReplicaCount: 5
  pollingInterval: 15
  cooldownPeriod: 60
  
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 60
        scaleDown:
          stabilizationWindowSeconds: 120
  
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "40"
    
    - type: memory
      metricType: Utilization
      metadata:
        value: "40"
    
    # HTTP requests trigger (disabled - using pure HPA mode: CPU + Memory only)
    # - type: prometheus
    #   metadata:
    #     serverAddress: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
    #     metricName: http_requests_rate
    #     query: |
    #       sum(rate(nginx_ingress_controller_requests{exported_namespace="ballandbeer",service="profile"}[1m]))
    #     threshold: "10"
    
    # ML-based trigger (disabled for data collection)
    # - type: prometheus
    #   metadata:
    #     serverAddress: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
    #     metricName: ml_predicted_replicas
    #     query: |
    #       ml_predicted_replicas{exported_service="profile"}
    #     threshold: "1"
