apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - scaledobject.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: authen
    app.kubernetes.io/part-of: ballandbeer