apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vault-pvc.yaml
  - vault-deployment.yaml
  - vault-service.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: infra
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: ballandbeer
